#!/bin/bash
meshName="SHEAR3D_TEST"
rm $meshName.mesh 
rm *.o *.out *.mod

gfortran -c Module_MeshTranslator.f90
gfortran -c TranslateMeshToBSC.f90
gfortran -o translateMesh.out Module_MeshTranslator.o TranslateMeshToBSC.o

./translateMesh.out $meshName.neu $meshName.mesh
#./translateMesh.out Box2D.neu TranslatedMesh.mesh
#./translateMesh.out Box2D.mesh TranslatedMesh.mesh
#./translateMesh.out Aerospike.neu TranslatedMesh.mesh
